version: '3'

services:
  frontend:
    build: 
      context: .
    image: react-docker
    container_name: banksystem_frontend
    env_file: .env
    ports:
      - "3001:3001"
    volumes:
      - ./:/home/app/react_docker
      - /home/app/react_docker/node_modules
    networks:
      - banksystem-network
    command: npm run start

networks:
  banksystem-network: